# @package _global_

# python run.py -m sweep=pd_control

defaults:
  - override /hydra/sweeper: optuna
  - override /hydra/sweeper/sampler: grid
  - override /hydra/launcher: joblib

optimized_metric: "nusselt"
hydra:
  mode: "MULTIRUN"
  launcher:
    n_jobs: 5
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    storage: "sqlite:///logs/optuna_baselines.db"
    study_name: Baselines
    direction: minimize
    n_jobs: 5
    n_trials: 100

    # hyperparameter search space
    params:
      seed: range(42, 79, step=1)
      sim.ra: choice(10_000, 100_000, 1_000_000)
      sim.episode_length: 400
      sim.dt: 0.025
      action_start: 0
      # fixed params
      controller: zero
      callbacks: sweep
