# @package _global_

# python run.py -m sweep=pd_control

defaults:
  - override /hydra/sweeper: optuna
  - override /hydra/sweeper/sampler: tpe
  - override /hydra/launcher: joblib

optimized_metric: "nusselt"
hydra:
  mode: "MULTIRUN"
  launcher:
    n_jobs: 5
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    storage: "sqlite:///logs/optuna_pdcontrol.db"
    study_name: Sweep-PD-NoMotion-10e6
    direction: minimize
    n_jobs: 5
    n_trials: 50

    # hyperparameter search space
    params:
      controller.kp: range(0, 1_000, step=10)
      controller.kd: range(0, 1_000_000, step=5000)
      # semi fixed params
      sim.ra: 1_000_000
      sim.episode_length: 300
      sim.dt: 0.025
      action_start: 0
      # fixed params
      controller: pd
      callbacks: sweep
