name: rbcdata
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - shenfun
  - pytorch
  - torchvision
  - pip
  - pip:
      - matplotlib
      - numpy
      - h5py
      - hydra-core
      - gymnasium
      - tqdm
