name: rbcdata
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - shenfun
  - pytorch
  - torchvision
  - pip
  - pip:
      - matplotlib
      - numpy
      - h5py
      - hydra-core
      - hydra-joblib-launcher
      - hydra-colorlog
      - gymnasium
      - tqdm
      - rootutils
