# Configuration file for the simulation when using single-agent (SA) version of the RBC controller
episode_length: 5
N: [64, 96]
N_obs: [8, 48]
ra: 10_000
pr: 0.7
dt: 0.025
bcT: [2, 1]
save_checkpoint_path: shenfun/checkpoint/RB_2D  # folder where checkpoints are stored during the simulation
load_checkpoint_path: ../data/checkpoints/ra10000/train/ # Upon reset: null means random initialization, otherwise from checkpoint file or randomly from a directory of checkpoints.