# Configuration file for the simulation when using single-agent (SA) version of the RBC controller
episode_length: 800
N: [64, 96]
N_obs: [8, 48]
ra: 10_000
pr: 0.7
dt: 0.025
bcT: [2, 1]
checkpoint_path: shenfun/checkpoint/RB_2D
