defaults:
  - sim/default
  - generate: full
  - override hydra/launcher: joblib

path: ../RayleighBenard-Dataset
count: 25
base_seed: 2710
dt: 0.1
segments: 10
action_scaling: 0.75
action_duration: 1.5

hydra:
  mode: "MULTIRUN"
  job:
    chdir: true
  sweep:
    dir: ./logs/generate/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: job${hydra.job.num}_ra${sim.ra}
  launcher:
    n_jobs: 4
