# Config file for running the Multi-Agent (MA) version of the RBC controller

defaults:
  - hydra: default
  - env: default
  - _self_

# Environment parameters
env:
  episode_length: 300
  checkpoint: ../../../data/checkpoints/ra10000/train/baseline42

# Stable baselines 3 parameters overrides
sb3:
  nr_processes: 2
  eval_episodes: 20 # just on rollout per worker, collecting nr_processes rollouts per evaluation
  train_steps: 100_000_000
  eval_every: 4 # eval_every * nr_processes total episodes completed before evaluation. So PPO has then already been updated for eval_every / episodes_update times (has seen so many datasets)
  train_checkpoint_every: 1 # same units as eval_every property.
  ppo:
    lr: 1e-3
    episodes_update: 1 # episodes_update * nr_processes total episodes per update
    batch_size: 500 # 1 * 20 * 200 = 4000 timesteps in dataset for update. For 8 batches it means 4000 / 8 = 500 timesteps per minibatch
    gamma: 0.99
    ent_coef: 0.2
