defaults:
  - hydra: default
  - paths: default
  - env: default
  - _self_

task: pdcontrol
seed: 44
interval: 1
render_mode: null
baseline: False

env:
  ra: 1_000_000
  checkpoint: "data/checkpoints/ra${env.ra}/train"
  episode_length: 30
  action_suration: 1.0
  dt: 0.025

controller:
  kp: 970
  kd: 2000
  bcT: [2, 1]
  limit: 0.75
  start: 0.0
  end: ${env.episode_length}
  action_duration: ${env.action_duration}
  nr_segments: ${env.action_segments}
