defaults:
  - hydra: default
  - paths: default
  - env: default
  - _self_

task: pdcontrol
seed: null
interval: 1
render_mode: rgb_array

hydra:
  job:
    chdir: true

# params
baseline: True
nr_episodes: 1

env:
  ra: 10_000
  checkpoint: null  #data/checkpoints/ra${env.ra}/test
  episode_length: 700
  action_duration: 1.5
  dt: 0.025

controller:
  kp: 970
  kd: 2000
  bcT: [2, 1]
  limit: 0.75
  start: 0.0
  end: ${env.episode_length}
  action_duration: ${env.action_duration}
  nr_segments: ${env.action_segments}
