defaults:
  - _self_
  - hydra: default
  - sim: default
  - controller: zero
  - sweep: null

seed: 42
interval: 40
checkpoint: null #../../../data/checkpoints/ra10000

action_segments: 10
action_start: 0
action_limit: 0.75
action_duration: 1.5

vis: true
vis_action: true
