defaults:
  - hydra: default
  - env: default
  - controller: zero
  - callbacks: default
  - sweep: null
  - _self_

seed: 42
interval: 5
render_mode: human

env:
  checkpoint: ../../../data/checkpoints/ra10000/train/baseline42
