defaults:
  - hydra: default
  - env: default
  - _self_

task: run
seed: 42
interval: 1
render_mode: null

env:
  ra: 100_000
  checkpoint: "data/checkpoints/ra1000000/train"
  episode_length: 120
  action_suration: 1.0
  dt: 0.05
