defaults:
  - sim/default
  - controller/zero

seed: 42
segments: 10
action_start: 20
action_scaling: 0.75
action_duration: 1.5
interval: 1

hydra:
  job:
    chdir: true
  run:
    dir: ./logs/run/${now:%m-%d-%H-%M-%S}/
