defaults:
  - sim/default
  - controller/zero

seed: 42

action_segments: 96
action_start: 0
action_limit: 0.75
action_duration: 1.5

interval: 20

hydra:
  job:
    chdir: true
  run:
    dir: ./logs/run/${now:%m-%d-%H-%M-%S}/
