defaults:
  - hydra: default
  - env: default
  - _self_

task: run
seed: 42
interval: 1
render_mode: null # null, "human" or "rgb_array"

env:
  ra: 10_000
  checkpoint: "data/checkpoints/ra1000000/train"
  episode_length: 120
  action_duration: 1
  dt: 0.05
