defaults:
  - hydra: default
  - env: default
  - _self_
  - generate: null

task: run
seed: null
interval: 1
render_mode: human # null, "human" or "rgb_array"

env:
  ra: 5_000_000
  checkpoint: "data/checkpoints/ra${env.ra}/train"
  episode_length: 120
  action_duration: 1
  dt: 0.025

hydra:
  job:
    chdir: true
