# Config file for running the Single-Agent (SA) version of the RBC controller

defaults:
  - hydra: default
  - sim: default
  - rl/ppo: default
  - _self_  # This will override the defaults if there are any conflicts
#  - callbacks: default
#  - sweep: null

seed: 42
callback_interval: 16 

action_segments: 10
action_start: 0
action_end: 800
action_limit: 0.75
action_duration: 1.5