# Config file for running the Single-Agent (SA) version of the RBC controller

defaults:
#  - _self_
  - hydra: default
  - sim: SA
  - ray: default
  - rl/ppo: default
#  - callbacks: default
#  - sweep: null

seed: 42
interval: 16  # Michiel: I think this is related to utils.callbacks, where it is used to determine the simulation step interval for which the callbacks are effective. Could have a more explanatory name.

action_segments: 10
action_start: 0 #400  # not sure if these are applicable to the SA case. TODO: I think we should always have time 0 even for checkpoint.
action_end: 800 #700
action_limit: 0.75
action_duration: 1.5

# Ray configuration (TODO move to above categorized configs section)
