# Config file for running the Single-Agent (SA) version of the RBC controller

defaults:
  - _self_
  - hydra: default
  - sim: SA
  - controller: zero
  - callbacks: default
  - sweep: null

seed: 42
interval: 16
checkpoint: null #../../../data/checkpoints/ra10000

action_segments: 10
action_start: 0 #400  # not sure if these are applicable to the SA case.
action_end: 800 #700
action_limit: 0.75
action_duration: 1.5