# Config file for running the Single-Agent (SA) version of the RBC controller

defaults:
  - hydra: default
  - env@train_env: default
  - env@test_env: default
  - _self_ # This will override the defaults if there are any conflicts

task: sbsa
seed: 42
ra: 10_000
dt: 0.05

train_env:
  ra: ${ra}
  dt: ${dt}
  episode_length: 50
  checkpoint: data/checkpoints/ra${ra}/train #/baseline42.chk.h5

eval_env:
  ra: ${ra}
  dt: ${dt}
  episode_length: 100
  checkpoint: data/checkpoints/ra${ra}/test #/baseline42.chk.h5


# Stable baselines 3 parameters overrides
sb3:
  nr_processes: 20
  nr_eval_processes: 5
  #eval_episodes: 5 # just on rollout per worker, collecting nr_processes rollouts per evaluation
  train_steps: 150_000
  eval_every: 5 # eval_every * nr_processes total episodes completed before evaluation. So PPO has then already been updated for eval_every / episodes_update times (has seen so many datasets)
  train_checkpoint_every: 5 # same units as eval_every property.
  frame_stack: 4 # number of observations to stack
  model: "sac"  #"ppo"
  reward_shaping: 0 # how much reward shaping, i.e. taking into account distance between cells, to apply (0 = no shaping, 1 = full shaping)
  sac:
    ent_coef: "auto"
  ppo:
    lr: 0.001
    episodes_update: 2 # episodes_update * nr_processes total episodes per update
    batch_size: 500 # 1 * 20 * 200 = 4000 timesteps in dataset for update. For 8 batches it means 4000 / 8 = 500 timesteps per minibatch
    gamma: 0.99
    ent_coef: 0.5
    vf_coef: 0.5
