# Config file for running the Single-Agent (SA) version of the RBC controller

defaults:
  - hydra: default
  - env@train_env: default
  - env@test_env: default
  - _self_ # This will override the defaults if there are any conflicts

task: sbsa
tags: null
notes: null
seed: null
ra: 10_000
dt: 0.05
action_duration: 1.5
reward_shaping: 0.15 # how much reward shaping, i.e. taking into account distance between cells, to apply (0 = no shaping, 1 = full shaping)

train_env:
  ra: ${ra}
  dt: ${dt}
  episode_length: 100
  # checkpoint: data/checkpoints/ra${ra}/train/baseline42.chk.h5
  checkpoint: data/checkpoints/ra${ra}/train/
  action_duration: ${action_duration}
  reward_shaping: ${reward_shaping}

test_env:
  ra: ${ra}
  dt: ${dt}
  episode_length: 300
  # checkpoint: data/checkpoints/ra${ra}/train/baseline42.chk.h5
  checkpoint: data/checkpoints/ra${ra}/test/
  action_duration: ${action_duration}
  reward_shaping: ${reward_shaping}


# Stable baselines 3 parameters overrides
sb3:
  nr_processes: 30
  nr_eval_processes: 10
  #eval_episodes: 5 # just on rollout per worker, collecting nr_processes rollouts per evaluation
  train_steps: 400_000
  eval_every: 10 # eval_every * nr_processes total episodes completed before evaluation. So PPO has then already been updated for eval_every / episodes_update times (has seen so many datasets)
  train_checkpoint_every: 10 # same units as eval_every property.
  frame_stack: 1 # number of observations to stack
  model: "ppo"  #"ppo"
  sac:
    ent_coef: "auto"
  ppo:
    lr: 0.001
    episodes_update: 1 # episodes_update * nr_processes total episodes per update
    batch_size: 500 # 1 * 20 * 200 = 4000 timesteps in dataset for update. For 8 batches it means 4000 / 8 = 500 timesteps per minibatch
    gamma: 0.99
    ent_coef: 0.01
    vf_coef: 0.5
    nr_neurons: 256
