# Config file for running the Single-Agent (SA) version of the RBC controller

defaults:
  - hydra: default
  - _self_ # This will override the defaults if there are any conflicts

task: sbsa_eval
ra: 10_000
experiment_dir: logs/sbsa/02-04-13-27-54
nr_episodes: 10
render_mode: "rgb_array" # "human" or "rgb_array"
fps: 4
