# Config file for running the Single-Agent (SA) version of the RBC controller

defaults:
  - hydra: default
  - _self_ # This will override the defaults if there are any conflicts

task: sbsa_eval
ra: 5_000_000
experiment_dir: logs/experiments/ra${ra}
nr_episodes: 20
render_mode: "rgb_array" # "human" or "rgb_array"
fps: 4
