# Config file for evaluating the Single-Agent (SA) version of the RBC controller

defaults:
  - hydra: default
  - env: default
  - _self_

# wandb configuration
task: sbsa_eval
tags:
  - eval

# experiment configuration
experiment_dir: logs/experiments/test
model_name: "best_model"
ra: 100_000

# fixed parameters
nr_episodes: 20
render_mode: "rgb_array" # "human" or "rgb_array"
fps: 4
action_duration: 1.5

env:
  ra: ${ra}
  dt: 0.025
  episode_length: 300
  checkpoint: data/checkpoints/ra${ra}/test/
  action_duration: ${action_duration}
