defaults:
  - dataset/default
  - override hydra/help: view_help
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - _self_

hydra:
  output_subdir: null
  run:
    dir: .

fps: 10
path: ???
